function h_ax = a4axis(h_fig, axis_position)

VariableDefault('h_fig', []);
VariableDefault('axis_position', [65, 123.5, 80, 50]);

if isempty(h_fig)
    h_fig = a4figure();
end

h_ax = axes(h_fig);

set(h_ax, ...
    'Color',                    'w', ...
    'XColor',                   'k', ...
    'YColor',                   'k', ...
    'Units',                    'normalized', ...
    'PositionConstraint',       'innerposition', ...
    'InnerPosition',            mmpos2normpos(axis_position), ...
    'PlotBoxAspectRatioMode',   'auto');
hold on;
