function h_fig = a4figure(orientation)
% A4FIGURE Create an axis on an A4 figure
%
%   FIGURE_HANDLE = a4figure(ORIENTATION) creates an A4 sized figure with
%   orientation ORIENTATION ('portrait' (default) or 'landscape'). The
%   handle to the figure is returned in FIGURE_HANDLE.
%
%   See also: a4axis, a4figure_text

VariableDefault('orientation', 'portrait');

if strcmp(orientation, 'portrait')
    paper_size = [21, 29.7];
elseif strcmp(orientation, 'landscape')
    paper_size = [29.7, 21];
else
    error('Wrong argument to a4figure.m');
end

h_fig = figure();
set(0, 'units', 'pixels');

% make sure figure fits on the screen
screen_size = get(0, 'screensize');
if strcmp(orientation, 'portrait')
    screen_position = [0, 0, round(screen_size(4)*21/29.7), screen_size(4)];
else
    screen_position = [0, 0, screen_size(4), round(screen_size(4)*21/29.7)];
end

set(h_fig, ...
    'Color',                'w', ...
    'DockControls',         'off', ...
    'MenuBar',              'none', ...
    'Name',                 '', ...
    'NumberTitle',          get(h_fig, 'NumberTitle'), ...
    'ToolBar',              'none', ...
    'Visible',              'on', ...
    'RendererMode',         'manual', ...
    'Renderer',             'painters', ...
    'Units',                'pixels', ...
    'Position',             screen_position, ...
    'Resize',               'off', ...
    'PaperPositionMode',    'manual', ...
    'PaperType',            'A4', ...
    'PaperOrientation',     orientation, ...
    'PaperUnits',           'centimeters', ...
    'PaperPosition',        [0, 0, paper_size(1), paper_size(2)], ...
    'PaperSize',            paper_size, ...
    'InvertHardcopy',       'off');