% Compare TF tuning across conditions (V, VT, T_Vstatic)
%
% This script analyzes temporal frequency tuning differences across experimental
% conditions. It reads the model fit information from tf_tuning_model_fits.csv
% (generated by tf_tuning_all_clusters_all_conditions.m) and classifies clusters
% based on their tuning properties.
%
% Analysis questions:
% 1. How many clusters are tuned to condition V (based on p_value_shuffle < 0.05)?
% 2. Of those NOT tuned in V, how many are tuned to VT?
% 3. Of those tuned in both V and VT, how many show different tuning characteristics?
%    - Different best model selected
%    - Same model but with significantly different parameters
% 4. Save classification results to CSV
%
% Output CSV columns:
%   - probe_id, cluster_id, region
%   - V_is_tuned, VT_is_tuned, T_Vstatic_is_tuned (boolean)
%   - tuning_category (e.g., "V_only", "VT_only", "both_similar", "both_different", "neither")
%   - V_best_model, VT_best_model, model_agreement (boolean)
%   - Parameter difference metrics (for clusters with same model in V and VT)
%
% See also: tf_tuning_all_clusters_all_conditions

%% Configuration

% Path to the model fits CSV file (relative to figures directory)
figure_dir = {'tf_tuning_curves'};
csv_filename = 'tf_tuning_model_fits.csv';

% Significance threshold
p_threshold = 0.05;

% Threshold for "significantly different" parameters (as fraction of parameter value)
param_diff_threshold = 0.1;  % 20% difference considered significant

%% Load data

ctl = RC2Analysis();

% Setup directory (same as plotting script)
ctl.setup_figures(figure_dir, true);  % Enable figure saving

% Construct full path to CSV file
csv_path = fullfile(ctl.figs.curr_dir, csv_filename);

if ~exist(csv_path, 'file')
    error('CSV file not found: %s\nPlease run tf_tuning_all_clusters_all_conditions.m first.', csv_path);
end

fprintf('Loading model fit data from:\n  %s\n\n', csv_path);
model_fits = readtable(csv_path);

fprintf('Total rows in CSV: %d\n', height(model_fits));

%% Load R² on mean data from model comparison CSVs

fprintf('\nLoading R² on mean data from model comparison CSVs...\n');
model_comp_dir = fullfile(ctl.path_config.formatted_data_dir, 'csvs', 'tf_tuning_curves');
model_comp_files = dir(fullfile(model_comp_dir, '*_model_comparison.csv'));

if isempty(model_comp_files)
    error('No model comparison CSV files found in: %s', model_comp_dir);
end

% Load all model comparison files and combine
all_rsq_data = [];
for ii = 1:length(model_comp_files)
    file_path = fullfile(model_comp_dir, model_comp_files(ii).name);
    temp_data = readtable(file_path);
    all_rsq_data = [all_rsq_data; temp_data];
end

fprintf('  Loaded %d rows from %d files\n\n', height(all_rsq_data), length(model_comp_files));

%% Reshape data for analysis

% Get unique clusters
unique_clusters = unique(model_fits(:, {'probe_id', 'cluster_id', 'region'}), 'rows');
n_clusters = height(unique_clusters);

fprintf('Unique clusters: %d\n', n_clusters);

% Extract maximum rsq_on_mean for each cluster in V and VT conditions
fprintf('Extracting max rsq_on_mean for V and VT conditions...\n');

max_rsq_V = nan(n_clusters, 1);
max_rsq_VT = nan(n_clusters, 1);

for ii = 1:n_clusters
    probe_id = unique_clusters.probe_id{ii};
    cluster_id = unique_clusters.cluster_id(ii);
    
    % Get rows for this cluster
    cluster_mask = strcmp(all_rsq_data.probe_id, probe_id) & ...
                   all_rsq_data.cluster_id == cluster_id;
    
    % Extract V condition rsq_on_mean
    v_mask = cluster_mask & strcmp(all_rsq_data.trial_group, 'V');
    if any(v_mask)
        max_rsq_V(ii) = max(all_rsq_data.rsq_on_mean(v_mask));
    end
    
    % Extract VT condition rsq_on_mean
    vt_mask = cluster_mask & strcmp(all_rsq_data.trial_group, 'VT');
    if any(vt_mask)
        max_rsq_VT(ii) = max(all_rsq_data.rsq_on_mean(vt_mask));
    end
end

fprintf('  Done extracting rsq_on_mean values\n');

% Filter clusters based on R² on mean: keep only clusters with rsq_on_mean > 0.65 for VT OR V
fprintf('Applying R² on mean filter (> 0.65 for VT OR V)...\n');

rsq_filter = (~isnan(max_rsq_V) & max_rsq_V > 0.65) | ...
             (~isnan(max_rsq_VT) & max_rsq_VT > 0.65);

unique_clusters = unique_clusters(rsq_filter, :);
max_rsq_V = max_rsq_V(rsq_filter);
max_rsq_VT = max_rsq_VT(rsq_filter);
n_clusters_filtered = height(unique_clusters);

fprintf('  Clusters before R² filter: %d\n', n_clusters);
fprintf('  Clusters after R² filter: %d\n\n', n_clusters_filtered);

n_clusters = n_clusters_filtered;

% Initialize results table
results = unique_clusters;
results.max_rsq_V = max_rsq_V;
results.max_rsq_VT = max_rsq_VT;
results.V_is_tuned = false(n_clusters, 1);
results.VT_is_tuned = false(n_clusters, 1);
results.T_Vstatic_is_tuned = false(n_clusters, 1);
results.V_p_value = nan(n_clusters, 1);
results.VT_p_value = nan(n_clusters, 1);
results.T_Vstatic_p_value = nan(n_clusters, 1);
results.V_best_model = cell(n_clusters, 1);
results.VT_best_model = cell(n_clusters, 1);
results.T_Vstatic_best_model = cell(n_clusters, 1);
results.V_rsq = nan(n_clusters, 1);
results.VT_rsq = nan(n_clusters, 1);
results.T_Vstatic_rsq = nan(n_clusters, 1);
results.model_agreement_V_VT = false(n_clusters, 1);
results.param_diff_metric = nan(n_clusters, 1);  % Model-specific parameter difference
results.params_are_similar = false(n_clusters, 1);
results.tuning_category = cell(n_clusters, 1);

%% Extract data for each cluster and condition

fprintf('Processing clusters...\n');

for ii = 1:n_clusters
    probe_id = results.probe_id{ii};
    cluster_id = results.cluster_id(ii);
    
    % Get rows for this cluster
    cluster_rows = strcmp(model_fits.probe_id, probe_id) & ...
                   model_fits.cluster_id == cluster_id;
    cluster_data = model_fits(cluster_rows, :);
    
    % Extract data for each condition
    conditions = {'V', 'VT', 'T_Vstatic'};
    for kk = 1:length(conditions)
        cond = conditions{kk};
        cond_row = strcmp(cluster_data.condition, cond);
        
        if any(cond_row)
            row_data = cluster_data(cond_row, :);
            
            % Tuning status
            results.([cond '_is_tuned'])(ii) = row_data.is_significant;
            results.([cond '_p_value'])(ii) = row_data.p_value_shuffle;
            results.([cond '_best_model']){ii} = row_data.best_model{1};
            results.([cond '_rsq'])(ii) = row_data.rsq;
        else
            results.([cond '_best_model']){ii} = 'N/A';
        end
    end
    
    % Check model agreement between V and VT
    if ~strcmp(results.V_best_model{ii}, 'N/A') && ~strcmp(results.VT_best_model{ii}, 'N/A')
        results.model_agreement_V_VT(ii) = strcmp(results.V_best_model{ii}, results.VT_best_model{ii});
        
        % If same model and both tuned, compare parameters using model-specific logic
        if results.model_agreement_V_VT(ii) && results.V_is_tuned(ii) && results.VT_is_tuned(ii)
            V_data = cluster_data(strcmp(cluster_data.condition, 'V'), :);
            VT_data = cluster_data(strcmp(cluster_data.condition, 'VT'), :);
            
            % Get model-specific parameters and compare
            model_type = results.V_best_model{ii};
            [param_diff, params_similar] = compare_model_params(model_type, V_data, VT_data, param_diff_threshold);
            
            results.param_diff_metric(ii) = param_diff;
            results.params_are_similar(ii) = params_similar;
        end
    end
end

fprintf('Done processing clusters.\n\n');

%% Categorize clusters

fprintf('Categorizing clusters...\n');

for ii = 1:n_clusters
    V_tuned = results.V_is_tuned(ii);
    VT_tuned = results.VT_is_tuned(ii);
    
    if ~V_tuned && ~VT_tuned
        results.tuning_category{ii} = 'neither';
    elseif V_tuned && ~VT_tuned
        results.tuning_category{ii} = 'V_only';
    elseif ~V_tuned && VT_tuned
        results.tuning_category{ii} = 'VT_only';
    elseif V_tuned && VT_tuned
        % Both tuned - check if similar
        if ~results.model_agreement_V_VT(ii)
            results.tuning_category{ii} = 'both_different_model';
        elseif results.params_are_similar(ii)
            results.tuning_category{ii} = 'both_similar';
        else
            results.tuning_category{ii} = 'both_different_params';
        end
    end
end

fprintf('Done categorizing.\n\n');

%% Focus on V significant + V R² > 0.65 clusters

fprintf('=== FILTERING FOR V SIGNIFICANT + V R² > 0.65 ===\n\n');

% Create mask for clusters that are significant for V AND have R² > 0.65 for V
focus_mask = results.V_is_tuned & results.max_rsq_V > 0.65;
n_focus_clusters = sum(focus_mask);

fprintf('Total clusters after initial R² filter (V OR VT): %d\n', n_clusters);
fprintf('Clusters with V significant AND V R² > 0.65: %d\n\n', n_focus_clusters);

% Add a flag to results table
results.is_focus_cluster = focus_mask;

%% Print summary statistics

fprintf('=== SUMMARY STATISTICS (ALL CLUSTERS) ===\n\n');

fprintf('R² filtering summary:\n');
fprintf('  Clusters with R² > 0.65 for V: %d\n', sum(~isnan(results.max_rsq_V) & results.max_rsq_V > 0.65));
fprintf('  Clusters with R² > 0.65 for VT: %d\n', sum(~isnan(results.max_rsq_VT) & results.max_rsq_VT > 0.65));
fprintf('  Clusters with R² > 0.65 for V OR VT: %d (total included)\n\n', n_clusters);

fprintf('Clusters meeting both significance AND R² > 0.65 criteria:\n');
n_V_sig_and_rsq = sum(results.V_is_tuned & results.max_rsq_V > 0.65);
n_VT_sig_and_rsq = sum(results.VT_is_tuned & results.max_rsq_VT > 0.65);
fprintf('  V (significant AND R² > 0.65): %d (%.1f%% of total)\n', n_V_sig_and_rsq, 100*n_V_sig_and_rsq/n_clusters);
fprintf('  VT (significant AND R² > 0.65): %d (%.1f%% of total)\n\n', n_VT_sig_and_rsq, 100*n_VT_sig_and_rsq/n_clusters);

fprintf('Question 1: How many clusters are tuned to condition V?\n');
n_V_tuned = sum(results.V_is_tuned);
n_V_not_tuned = sum(~results.V_is_tuned);
fprintf('  Tuned to V: %d (%.1f%%)\n', n_V_tuned, 100*n_V_tuned/n_clusters);
fprintf('  NOT tuned to V: %d (%.1f%%)\n\n', n_V_not_tuned, 100*n_V_not_tuned/n_clusters);

fprintf('Question 2: Of those NOT tuned in V, how many are tuned to VT?\n');
not_V_idx = ~results.V_is_tuned;
n_not_V_but_VT = sum(not_V_idx & results.VT_is_tuned);
fprintf('  NOT V but tuned to VT: %d (%.1f%% of non-V-tuned)\n\n', ...
    n_not_V_but_VT, 100*n_not_V_but_VT/n_V_not_tuned);

fprintf('Question 3: Of those tuned to V, how many are also tuned to VT?\n');
V_idx = results.V_is_tuned;
n_V_and_VT = sum(V_idx & results.VT_is_tuned);
fprintf('  Tuned to both V and VT: %d (%.1f%% of V-tuned)\n', ...
    n_V_and_VT, 100*n_V_and_VT/n_V_tuned);

fprintf('  Of those tuned to both:\n');
both_idx = V_idx & results.VT_is_tuned;
n_same_model = sum(both_idx & results.model_agreement_V_VT);
n_diff_model = sum(both_idx & ~results.model_agreement_V_VT);
fprintf('    Same model: %d (%.1f%%)\n', n_same_model, 100*n_same_model/n_V_and_VT);
fprintf('    Different model: %d (%.1f%%)\n', n_diff_model, 100*n_diff_model/n_V_and_VT);

same_model_idx = both_idx & results.model_agreement_V_VT;
n_similar_params = sum(same_model_idx & results.params_are_similar);
n_diff_params = sum(same_model_idx & ~results.params_are_similar);
fprintf('    Same model, similar parameters: %d (%.1f%% of same-model)\n', ...
    n_similar_params, 100*n_similar_params/max(n_same_model,1));
fprintf('    Same model, different parameters: %d (%.1f%% of same-model)\n\n', ...
    n_diff_params, 100*n_diff_params/max(n_same_model,1));

fprintf('Overall distribution by category:\n');
categories = unique(results.tuning_category);
for ii = 1:length(categories)
    cat = categories{ii};
    n_cat = sum(strcmp(results.tuning_category, cat));
    fprintf('  %s: %d (%.1f%%)\n', cat, n_cat, 100*n_cat/n_clusters);
end
fprintf('\n');

%% Summary for FOCUS clusters (V significant + V R² > 0.65)

fprintf('=== FOCUS ANALYSIS: V Significant + V R² > 0.65 (n=%d) ===\n\n', n_focus_clusters);

if n_focus_clusters > 0
    % Category 1: V = VT (same model)
    % Note: Only requires same model selected, not that VT is significant
    v_eq_vt_mask = focus_mask & results.model_agreement_V_VT;
    n_v_eq_vt = sum(v_eq_vt_mask);
    
    % For those with same model, check if both are tuned to compare parameters
    v_eq_vt_both_tuned = v_eq_vt_mask & results.VT_is_tuned;
    n_v_eq_vt_similar = sum(v_eq_vt_both_tuned & results.params_are_similar);
    n_v_eq_vt_different = sum(v_eq_vt_both_tuned & ~results.params_are_similar);
    
    fprintf('Category 1: V = VT (same model)\n');
    fprintf('  Requirements: V sig + V R²>0.65, same model as VT\n');
    fprintf('  Total: %d (%.1f%% of focus clusters)\n', n_v_eq_vt, 100*n_v_eq_vt/n_focus_clusters);
    fprintf('    Of these, both V and VT significant: %d (%.1f%%)\n', sum(v_eq_vt_both_tuned), 100*sum(v_eq_vt_both_tuned)/max(n_v_eq_vt,1));
    fprintf('      Similar parameters: %d (%.1f%% of both-tuned)\n', n_v_eq_vt_similar, 100*n_v_eq_vt_similar/max(sum(v_eq_vt_both_tuned),1));
    fprintf('      Different parameters: %d (%.1f%% of both-tuned)\n\n', n_v_eq_vt_different, 100*n_v_eq_vt_different/max(sum(v_eq_vt_both_tuned),1));
    
    % Category 2 & 3: V ≠ VT (different model)
    % Will be further divided in second script
    v_neq_vt_mask = focus_mask & ~results.model_agreement_V_VT;
    n_v_neq_vt = sum(v_neq_vt_mask);
    
    fprintf('Category 2 & 3: V ≠ VT (different model)\n');
    fprintf('  Requirements: V sig + V R²>0.65, different model from VT\n');
    fprintf('  Total: %d (%.1f%% of focus clusters)\n', n_v_neq_vt, 100*n_v_neq_vt/n_focus_clusters);
    fprintf('  (Will be further categorized in VT vs T_Vstatic comparison)\n\n');
    
    fprintf('Distribution of focus clusters by V vs VT category:\n');
    for ii = 1:length(categories)
        cat = categories{ii};
        n_cat = sum(focus_mask & strcmp(results.tuning_category, cat));
        if n_cat > 0
            fprintf('  %s: %d (%.1f%%)\n', cat, n_cat, 100*n_cat/n_focus_clusters);
        end
    end
    fprintf('\n');
else
    fprintf('No clusters meet the focus criteria.\n\n');
end

%% Save results to CSV

output_filename = fullfile(ctl.figs.curr_dir, 'tf_tuning_comparison_across_conditions.csv');
writetable(results, output_filename);

fprintf('Results saved to:\n  %s\n\n', output_filename);

%% Visualize fitted curves by category

fprintf('Creating category visualization figures...\n');
fprintf('Figures will be saved to: %s\n\n', ctl.figs.curr_dir);

% Filter results to only focus clusters for visualization
fprintf('Preparing to visualize FOCUS clusters only (V significant + V R² > 0.65)...\n');
focus_results = results(focus_mask, :);
n_focus_clusters_viz = height(focus_results);

if n_focus_clusters_viz == 0
    fprintf('  No focus clusters to visualize.\n\n');
    fprintf('=== Analysis complete ===\n');
    fprintf('Output CSV: tf_tuning_comparison_across_conditions.csv\n');
    return;
end

fprintf('  Will visualize %d focus clusters\n\n', n_focus_clusters_viz);

% Get unique probe_ids to load tuning data
unique_probes = unique(focus_results.probe_id);

% Build lookup structure: probe_id -> cluster_id -> condition -> tuning_data
tuning_lookup = struct();

for ii = 1:length(unique_probes)
    probe_id = unique_probes{ii};
    
    % Load tuning curves for this probe
    tbl = ctl.load_tf_tuning_curves(probe_id);
    
    % Store in lookup structure
    tuning_lookup.(matlab.lang.makeValidName(probe_id)) = struct();
    
    for kk = 1:length(tbl.trial_groups)
        trial_group = tbl.trial_groups{kk};
        tuning_curves = tbl.tuning_curves{kk};
        
        for jj = 1:length(tuning_curves)
            tc = tuning_curves(jj);
            cluster_key = sprintf('cluster_%d', tc.cluster_id);
            
            if ~isfield(tuning_lookup.(matlab.lang.makeValidName(probe_id)), cluster_key)
                tuning_lookup.(matlab.lang.makeValidName(probe_id)).(cluster_key) = struct();
            end
            
            tuning_lookup.(matlab.lang.makeValidName(probe_id)).(cluster_key).(trial_group) = tc;
        end
    end
end

fprintf('Loaded tuning data for %d probes.\n', length(unique_probes));

% Define categories to plot
plot_categories = {'neither', 'V_only', 'VT_only', 'both_similar', 'both_different_params', 'both_different_model'};

% Plot each category
for cat_idx = 1:length(plot_categories)
    cat = plot_categories{cat_idx};
    
    % Get clusters in this category (from focus clusters only)
    cat_clusters = strcmp(focus_results.tuning_category, cat);
    n_cat_clusters = sum(cat_clusters);
    
    fprintf('  Plotting category: %s (%d clusters)\n', cat, n_cat_clusters);
    
    if n_cat_clusters == 0
        fprintf('    Skipping - no clusters in this category.\n');
        continue;
    end
    
    % Generate distinct colors for each cluster in this category
    cluster_indices = find(cat_clusters);
    colors = lines(n_cat_clusters);
    color_map = containers.Map('KeyType', 'double', 'ValueType', 'any');
    for idx = 1:n_cat_clusters
        color_map(cluster_indices(idx)) = colors(idx, :);
    end
    
    % Create figure
    h_fig = ctl.figs.a4figure('landscape');
    
    % Create subplots: VT (left) and V (right)
    subplot(1, 2, 1);
    h_ax_VT = gca;
    hold on;
    title('Condition VT');
    xlabel('Temporal Frequency (Hz)');
    ylabel('Firing Rate (Hz)');
    
    subplot(1, 2, 2);
    h_ax_V = gca;
    hold on;
    title('Condition V');
    xlabel('Temporal Frequency (Hz)');
    ylabel('Firing Rate (Hz)');
    
    % Collect all fitted curves for mean/median calculation
    V_curves = [];
    VT_curves = [];
    common_x = [];
    
    % Plot individual cluster curves
    for ii = 1:n_focus_clusters_viz
        if ~cat_clusters(ii)
            continue;
        end
        
        probe_id = focus_results.probe_id{ii};
        cluster_id = focus_results.cluster_id(ii);
        
        probe_key = matlab.lang.makeValidName(probe_id);
        cluster_key = sprintf('cluster_%d', cluster_id);
        
        % Check if data exists
        if ~isfield(tuning_lookup, probe_key) || ...
           ~isfield(tuning_lookup.(probe_key), cluster_key)
            continue;
        end
        
        cluster_data = tuning_lookup.(probe_key).(cluster_key);
        cluster_color = color_map(ii);
        
        % Plot V condition
        if isfield(cluster_data, 'V')
            tc_V = cluster_data.V;
            [x_fit, y_fit] = evaluate_fitted_curve(tc_V);
            
            if ~isempty(y_fit)
                plot(h_ax_V, x_fit, y_fit, 'Color', cluster_color, 'LineWidth', 1.5);
                
                % Store for mean calculation
                if isempty(common_x)
                    common_x = x_fit;
                    V_curves = zeros(length(x_fit), n_cat_clusters);
                end
                V_curves(:, ii) = y_fit;
            end
        end
        
        % Plot VT condition
        if isfield(cluster_data, 'VT')
            tc_VT = cluster_data.VT;
            [x_fit, y_fit] = evaluate_fitted_curve(tc_VT);
            
            if ~isempty(y_fit)
                plot(h_ax_VT, x_fit, y_fit, 'Color', cluster_color, 'LineWidth', 1.5);
                
                % Store for mean calculation
                if isempty(common_x)
                    common_x = x_fit;
                    VT_curves = zeros(length(x_fit), n_cat_clusters);
                end
                VT_curves(:, ii) = y_fit;
            end
        end
    end
    
    % Plot mean/median curves
    if ~isempty(common_x)
        % Remove all-zero columns (clusters not in this category)
        V_curves = V_curves(:, any(V_curves, 1));
        VT_curves = VT_curves(:, any(VT_curves, 1));
        
        if ~isempty(V_curves)
            V_mean = nanmean(V_curves, 2);
            plot(h_ax_V, common_x, V_mean, 'k', 'LineWidth', 3);
        end
        
        if ~isempty(VT_curves)
            VT_mean = nanmean(VT_curves, 2);
            plot(h_ax_VT, common_x, VT_mean, 'k', 'LineWidth', 3);
        end
    end
    
    % Make axes equal
    if ~isempty(common_x)
        xlim(h_ax_V, [min(common_x), max(common_x)]);
        xlim(h_ax_VT, [min(common_x), max(common_x)]);
        
        y_max = max([ylim(h_ax_V), ylim(h_ax_VT)]);
        ylim(h_ax_V, [0, y_max]);
        ylim(h_ax_VT, [0, y_max]);
    end
    
    % Add cluster count to figure
    annotation('textbox', [0.5, 0.95, 0, 0], 'String', sprintf('n = %d clusters', n_cat_clusters), ...
        'HorizontalAlignment', 'center', 'VerticalAlignment', 'top', ...
        'FontSize', 10, 'FontWeight', 'bold', 'EdgeColor', 'none');
    
    % Save figure (delete existing file first to allow overwriting)
    fig_filename = sprintf('tf_tuning_category_%s.pdf', cat);
    full_path = fullfile(ctl.figs.curr_dir, fig_filename);
    if exist(full_path, 'file')
        delete(full_path);
    end
    ctl.figs.save_fig(fig_filename);
    fprintf('    Saved: %s\n', full_path);
end

fprintf('Category figures saved.\n\n');

fprintf('=== Analysis complete ===\n');
fprintf('Output CSV: tf_tuning_comparison_across_conditions.csv\n');
fprintf('Category figures: tf_tuning_category_*.pdf\n');


%% Helper function to evaluate fitted curve

function [x_fit, y_fit] = evaluate_fitted_curve(tuning)
    % Evaluate the fitted model for a tuning curve
    
    % Get x range
    if isfield(tuning, 'bin_centers') && ~isempty(tuning.bin_centers)
        x_min = min(tuning.bin_centers);
        x_max = max(tuning.bin_centers);
        x_fit = linspace(x_min, x_max, 100);
    else
        x_fit = [];
        y_fit = [];
        return;
    end
    
    % Get model info
    if ~isfield(tuning, 'shuffled') || ~isfield(tuning.shuffled, 'best_model')
        y_fit = [];
        return;
    end
    
    model_type = tuning.shuffled.best_model;
    
    if isfield(tuning.shuffled, 'best_model_info')
        params = tuning.shuffled.best_model_info.beta;
    elseif isfield(tuning.shuffled, 'beta')
        params = tuning.shuffled.beta;
    else
        y_fit = [];
        return;
    end
    
    % Evaluate model
    switch model_type
        case 'linear'
            y_fit = polyval(params, x_fit);
            
        case 'quadratic'
            y_fit = polyval(params, x_fit);
            
        case 'cubic'
            y_fit = polyval(params, x_fit);
            
        case 'gaussian'
            % params = [amplitude, mu, sigma, baseline]
            if length(params) >= 4
                y_fit = params(1) * exp(-(x_fit - params(2)).^2 / (2*params(3)^2)) + params(4);
            else
                y_fit = [];
            end
            
        case 'asymmetric_gaussian'
            % params = [R_max, x_max, sigma_minus, sigma_plus]
            if length(params) >= 4
                % Use ModelSelectionTuning class if available
                try
                    y_fit = ModelSelectionTuning.asymmetric_gaussian_static(params, x_fit);
                catch
                    % Fallback implementation
                    sigma = (x_fit < params(2)) * params(3) + (x_fit >= params(2)) * params(4);
                    y_fit = params(1) * exp(-((x_fit - params(2)).^2) ./ (2 * sigma.^2));
                end
            else
                y_fit = [];
            end
            
        case 'sigmoid'
            % params = [amplitude, k, x0, baseline]
            if length(params) >= 4
                y_fit = params(1) ./ (1 + exp(-params(2) * (x_fit - params(3)))) + params(4);
            else
                y_fit = [];
            end
            
        otherwise
            y_fit = [];
    end
end


function [param_diff_metric, params_similar] = compare_model_params(model_type, data1, data2, threshold)
%%compare_model_params Compare model parameters based on model type
%
%   [DIFF, SIMILAR] = compare_model_params(MODEL_TYPE, DATA1, DATA2, THRESHOLD)
%   Returns a metric of parameter difference and whether parameters are similar.

    switch model_type
        case {'linear', 'quadratic', 'cubic'}
            % For polynomials, check if we have individual coefficient columns
            % If not available, we can't do a meaningful comparison
            % (the CSV may not store polynomial coefficients separately)
            
            % Try to compare R² values as a proxy
            if ~isnan(data1.rsq) && ~isnan(data2.rsq)
                param_diff_metric = abs(data1.rsq - data2.rsq);
                params_similar = param_diff_metric < threshold;
            else
                param_diff_metric = nan;
                params_similar = false;
            end
            
        case 'gaussian'
            % Gaussian: [amplitude, mu, sigma, baseline]
            if ~ismember('param_amplitude', data1.Properties.VariableNames) || ...
               ~ismember('param_center', data1.Properties.VariableNames) || ...
               ~ismember('param_sigma_or_sigma_minus', data1.Properties.VariableNames)
                param_diff_metric = nan;
                params_similar = false;
                return;
            end
            
            params1 = [data1.param_amplitude, data1.param_center, data1.param_sigma_or_sigma_minus];
            params2 = [data2.param_amplitude, data2.param_center, data2.param_sigma_or_sigma_minus];
            
            if any(isnan(params1)) || any(isnan(params2))
                param_diff_metric = nan;
                params_similar = false;
                return;
            end
            
            % Compare key parameters: center, amplitude, width
            center_diff = abs(params1(2) - params2(2)) / max(abs([params1(2), params2(2)]));
            amp_diff = abs(params1(1) - params2(1)) / max(abs([params1(1), params2(1)]));
            width_diff = abs(params1(3) - params2(3)) / max(abs([params1(3), params2(3)]));
            
            % Use max difference as metric
            param_diff_metric = max([center_diff, amp_diff, width_diff]);
            params_similar = all([center_diff, amp_diff, width_diff] < threshold);
            
        case 'asymmetric_gaussian'
            % Asymmetric Gaussian: [R_max, x_max, sigma_minus, sigma_plus]
            if ~ismember('param_amplitude', data1.Properties.VariableNames) || ...
               ~ismember('param_center', data1.Properties.VariableNames) || ...
               ~ismember('param_sigma_or_sigma_minus', data1.Properties.VariableNames) || ...
               ~ismember('param_sigma_plus', data1.Properties.VariableNames)
                param_diff_metric = nan;
                params_similar = false;
                return;
            end
            
            params1 = [data1.param_amplitude, data1.param_center, data1.param_sigma_or_sigma_minus, data1.param_sigma_plus];
            params2 = [data2.param_amplitude, data2.param_center, data2.param_sigma_or_sigma_minus, data2.param_sigma_plus];
            
            if any(isnan(params1)) || any(isnan(params2))
                param_diff_metric = nan;
                params_similar = false;
                return;
            end
            
            % Compare key parameters
            center_diff = abs(params1(2) - params2(2)) / max(abs([params1(2), params2(2)]));
            amp_diff = abs(params1(1) - params2(1)) / max(abs([params1(1), params2(1)]));
            sigma_minus_diff = abs(params1(3) - params2(3)) / max(abs([params1(3), params2(3)]));
            sigma_plus_diff = abs(params1(4) - params2(4)) / max(abs([params1(4), params2(4)]));
            
            % Use max difference as metric
            param_diff_metric = max([center_diff, amp_diff, sigma_minus_diff, sigma_plus_diff]);
            params_similar = all([center_diff, amp_diff, sigma_minus_diff, sigma_plus_diff] < threshold);
            
        case 'sigmoid'
            % Sigmoid: [amplitude, k, x0, baseline]
            if ~ismember('param_amplitude', data1.Properties.VariableNames) || ...
               ~ismember('param_steepness', data1.Properties.VariableNames) || ...
               ~ismember('param_center', data1.Properties.VariableNames)
                param_diff_metric = nan;
                params_similar = false;
                return;
            end
            
            params1 = [data1.param_amplitude, data1.param_steepness, data1.param_center];
            params2 = [data2.param_amplitude, data2.param_steepness, data2.param_center];
            
            if any(isnan(params1)) || any(isnan(params2))
                param_diff_metric = nan;
                params_similar = false;
                return;
            end
            
            % Compare key parameters
            center_diff = abs(params1(3) - params2(3)) / max(abs([params1(3), params2(3)]));
            amp_diff = abs(params1(1) - params2(1)) / max(abs([params1(1), params2(1)]));
            steep_diff = abs(params1(2) - params2(2)) / max(abs([params1(2), params2(2)]));
            
            % Use max difference as metric
            param_diff_metric = max([center_diff, amp_diff, steep_diff]);
            params_similar = all([center_diff, amp_diff, steep_diff] < threshold);
            
        otherwise
            param_diff_metric = nan;
            params_similar = false;
    end
end
