function tab = readsvmtable(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CAA1112416REC1REC2REC3 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  CAA1112416REC1REC2REC3 = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  CAA1112416rec1rec2rec3 = importfile("C:\Users\Lee\Documents\mvelez\data\summary_data\stationary_vs_motion_fr\CAA-1112416_rec1_rec2_rec3.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-May-2021 18:44:01

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "probe_name", "cluster_id", "cluster_region", "cluster_depth", "cluster_from_tip", "protocol", "replay_of", "trial_id", "stationary_firing_rate", "time_stationary", "motion_firing_rate", "time_motion", "vis_stim"];
opts.VariableTypes = ["double", "categorical", "double", "double", "double", "double", "categorical", "string", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "replay_of", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["probe_name", "protocol", "replay_of"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "cluster_region", "TrimNonNumeric", true);
opts = setvaropts(opts, "cluster_region", "ThousandsSeparator", ",");

% Import the data
tab = readtable(filename, opts);

end