"""Pipeline regression test — pins per-cluster CV-bps against an archived baseline.

Replaces the MATLAB parity claim (rc2-glm-compare, retired 2026-04-29) as
the production trust signal after the onset-kernel removal. The baseline
is a small per-cluster CV-bps reference (12 clusters, 3 from each probe)
generated once from the FIRST 4-probe run with the new defaults
(``include_history=True``, ``include_onset_kernel=False``). Subsequent
``rc2-glm`` runs on the same formatted data must reproduce those numbers
within ``±0.01 bps`` per cluster.

Skips cleanly when:
- the reference CSV doesn't exist yet (initial bootstrap state)
- the local formatted-data dir is missing (CI / fresh checkout)

The reference CSV ``data/regression_baseline.csv`` is regenerated by
running ``rc2-glm`` with default config and copying the rows for the 12
named (probe_id, cluster_id) pairs.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

REFERENCE_CSV = Path(__file__).parent / "data" / "regression_baseline.csv"
LOCAL_DATA_ROOT = Path("/Users/lauraporta/local_data/motion_clouds")
GLM_CURRENT_DIR = LOCAL_DATA_ROOT / "figures" / "glm" / "current"
TOLERANCE_BPS = 0.01

# Twelve regression clusters: 3 per probe spanning low / median / high
# CV-bps in the legacy with-onset 4-probe run. Picked so the regression
# test exercises the full performance range, not just the well-fitted
# top of the distribution.
REGRESSION_CLUSTERS: tuple[tuple[str, int], ...] = (
    # CAA-1123243_rec1 (n=33 GLM-fit clusters; legacy cv_bps range [-11.8, -1.1])
    ("CAA-1123243_rec1", 116),  # mid: Speed+SF historically (the canonical example cluster)
    ("CAA-1123243_rec1", 339),  # low: -11.79 bps; the canonical fragile cluster
    ("CAA-1123243_rec1", 118),  # high: -1.10 bps; Speed-only
    # CAA-1123244_rec1 (n=13; range [-3.57, -1.25])
    ("CAA-1123244_rec1", 146),  # low: -3.57 bps; Speed
    ("CAA-1123244_rec1", 80),   # mid: -2.45 bps; Speed+TF
    ("CAA-1123244_rec1", 162),  # high: -1.25 bps; Speed
    # CAA-1123466_rec1 (n=32; range [-7.84, -1.34])
    ("CAA-1123466_rec1", 14),   # low: -7.84 bps; Speed
    ("CAA-1123466_rec1", 162),  # mid: -2.69 bps; Speed (note: same id as CAA-1123244 c162; different probe)
    ("CAA-1123466_rec1", 70),   # high: -1.34 bps; Speed
    # CAA-1123467_rec1 (n=10; range [-4.63, -1.59])
    ("CAA-1123467_rec1", 409),  # low: -4.63 bps; Speed+TF
    ("CAA-1123467_rec1", 517),  # mid: -2.20 bps; Null (no stimulus terms selected — sanity case)
    ("CAA-1123467_rec1", 564),  # high: -1.59 bps; Speed
)


@pytest.mark.skipif(
    not REFERENCE_CSV.exists(),
    reason=(
        "regression baseline not yet generated — run rc2-glm with default "
        "config on the 4 probes, then copy the per-cluster CV-bps for the "
        "12 REGRESSION_CLUSTERS into data/regression_baseline.csv"
    ),
)
@pytest.mark.skipif(
    not (GLM_CURRENT_DIR / "glm_model_comparison.csv").exists(),
    reason=(
        "no fresh rc2-glm output at glm/current/ to compare against — "
        "run rc2-glm with default config first"
    ),
)
def test_per_cluster_cv_bps_within_tolerance():
    """Each regression cluster's Selected CV-bps must match the baseline."""
    baseline = pd.read_csv(REFERENCE_CSV)
    baseline["key"] = list(zip(baseline["probe_id"], baseline["cluster_id"]))
    baseline_lookup = dict(zip(baseline["key"], baseline["time_Selected_cv_bps"]))

    fresh = pd.read_csv(GLM_CURRENT_DIR / "glm_model_comparison.csv")
    fresh["key"] = list(zip(fresh["probe_id"], fresh["cluster_id"]))
    fresh_lookup = dict(zip(fresh["key"], fresh["time_Selected_cv_bps"]))

    failures: list[str] = []
    for probe, cluster in REGRESSION_CLUSTERS:
        key = (probe, int(cluster))
        ref = baseline_lookup.get(key)
        cur = fresh_lookup.get(key)
        if ref is None:
            failures.append(f"{probe} cluster {cluster}: missing from baseline")
            continue
        if cur is None:
            failures.append(f"{probe} cluster {cluster}: missing from fresh run")
            continue
        if abs(cur - ref) > TOLERANCE_BPS:
            failures.append(
                f"{probe} cluster {cluster}: cv_bps={cur:+.4f} vs "
                f"baseline {ref:+.4f}, |Δ|={abs(cur - ref):.4f} > "
                f"{TOLERANCE_BPS}"
            )

    if failures:
        pytest.fail(
            f"{len(failures)} regression check(s) failed:\n  " +
            "\n  ".join(failures)
        )


def test_regression_clusters_metadata():
    """Sanity: 12 clusters, 3 per probe, all probe IDs valid."""
    assert len(REGRESSION_CLUSTERS) == 12
    by_probe: dict[str, int] = {}
    for probe, _ in REGRESSION_CLUSTERS:
        by_probe[probe] = by_probe.get(probe, 0) + 1
    assert all(n == 3 for n in by_probe.values()), \
        f"expected 3 clusters per probe; got {by_probe}"
    assert set(by_probe.keys()) == {
        "CAA-1123243_rec1", "CAA-1123244_rec1",
        "CAA-1123466_rec1", "CAA-1123467_rec1",
    }
